/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangKamiRouteImport } from './routes/tentang-kami'
import { Route as TemukanKamiRouteImport } from './routes/temukan-kami'
import { Route as MengapaSoysuRouteImport } from './routes/mengapa-soysu'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdukIndexRouteImport } from './routes/produk/index'
import { Route as ArtikelIndexRouteImport } from './routes/artikel/index'
import { Route as ProdukSlugRouteImport } from './routes/produk/$slug'
import { Route as ArtikelSlugRouteImport } from './routes/artikel/$slug'

const TentangKamiRoute = TentangKamiRouteImport.update({
  id: '/tentang-kami',
  path: '/tentang-kami',
  getParentRoute: () => rootRouteImport,
} as any)
const TemukanKamiRoute = TemukanKamiRouteImport.update({
  id: '/temukan-kami',
  path: '/temukan-kami',
  getParentRoute: () => rootRouteImport,
} as any)
const MengapaSoysuRoute = MengapaSoysuRouteImport.update({
  id: '/mengapa-soysu',
  path: '/mengapa-soysu',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukIndexRoute = ProdukIndexRouteImport.update({
  id: '/produk/',
  path: '/produk/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelIndexRoute = ArtikelIndexRouteImport.update({
  id: '/artikel/',
  path: '/artikel/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukSlugRoute = ProdukSlugRouteImport.update({
  id: '/produk/$slug',
  path: '/produk/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelSlugRoute = ArtikelSlugRouteImport.update({
  id: '/artikel/$slug',
  path: '/artikel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontak': typeof KontakRoute
  '/mengapa-soysu': typeof MengapaSoysuRoute
  '/temukan-kami': typeof TemukanKamiRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/artikel/': typeof ArtikelIndexRoute
  '/produk/': typeof ProdukIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontak': typeof KontakRoute
  '/mengapa-soysu': typeof MengapaSoysuRoute
  '/temukan-kami': typeof TemukanKamiRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/artikel': typeof ArtikelIndexRoute
  '/produk': typeof ProdukIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontak': typeof KontakRoute
  '/mengapa-soysu': typeof MengapaSoysuRoute
  '/temukan-kami': typeof TemukanKamiRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/artikel/': typeof ArtikelIndexRoute
  '/produk/': typeof ProdukIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kontak'
    | '/mengapa-soysu'
    | '/temukan-kami'
    | '/tentang-kami'
    | '/artikel/$slug'
    | '/produk/$slug'
    | '/artikel/'
    | '/produk/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kontak'
    | '/mengapa-soysu'
    | '/temukan-kami'
    | '/tentang-kami'
    | '/artikel/$slug'
    | '/produk/$slug'
    | '/artikel'
    | '/produk'
  id:
    | '__root__'
    | '/'
    | '/kontak'
    | '/mengapa-soysu'
    | '/temukan-kami'
    | '/tentang-kami'
    | '/artikel/$slug'
    | '/produk/$slug'
    | '/artikel/'
    | '/produk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontakRoute: typeof KontakRoute
  MengapaSoysuRoute: typeof MengapaSoysuRoute
  TemukanKamiRoute: typeof TemukanKamiRoute
  TentangKamiRoute: typeof TentangKamiRoute
  ArtikelSlugRoute: typeof ArtikelSlugRoute
  ProdukSlugRoute: typeof ProdukSlugRoute
  ArtikelIndexRoute: typeof ArtikelIndexRoute
  ProdukIndexRoute: typeof ProdukIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang-kami': {
      id: '/tentang-kami'
      path: '/tentang-kami'
      fullPath: '/tentang-kami'
      preLoaderRoute: typeof TentangKamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temukan-kami': {
      id: '/temukan-kami'
      path: '/temukan-kami'
      fullPath: '/temukan-kami'
      preLoaderRoute: typeof TemukanKamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mengapa-soysu': {
      id: '/mengapa-soysu'
      path: '/mengapa-soysu'
      fullPath: '/mengapa-soysu'
      preLoaderRoute: typeof MengapaSoysuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/': {
      id: '/produk/'
      path: '/produk'
      fullPath: '/produk/'
      preLoaderRoute: typeof ProdukIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel/': {
      id: '/artikel/'
      path: '/artikel'
      fullPath: '/artikel/'
      preLoaderRoute: typeof ArtikelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/$slug': {
      id: '/produk/$slug'
      path: '/produk/$slug'
      fullPath: '/produk/$slug'
      preLoaderRoute: typeof ProdukSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel/$slug': {
      id: '/artikel/$slug'
      path: '/artikel/$slug'
      fullPath: '/artikel/$slug'
      preLoaderRoute: typeof ArtikelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontakRoute: KontakRoute,
  MengapaSoysuRoute: MengapaSoysuRoute,
  TemukanKamiRoute: TemukanKamiRoute,
  TentangKamiRoute: TentangKamiRoute,
  ArtikelSlugRoute: ArtikelSlugRoute,
  ProdukSlugRoute: ProdukSlugRoute,
  ArtikelIndexRoute: ArtikelIndexRoute,
  ProdukIndexRoute: ProdukIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
